#!/bin/bash

# sudo pip3 install rst2html5
# pygmentize -S monokai -f html > monokai.css
# rst2html5 --stylesheet=monokai.css test.rst > test.html

for filename in *.rst; do
	# Line 20: SE extension: :italics:`abc <def>` will generate a link like so: <i><a href="def">abc</a></i>
	# Line 21: SE extension: change <em class="i"> to <i>

	rst2html5 "${filename}" \
	| perl -0777 -pe "s|.+<body>||s" \
	| perl -0777 -pe "s|</body>.*||s" \
	| sed --regexp-extended 's|    |\t|g' \
	| sed --regexp-extended 's|<span></span>||g' \
	| sed --regexp-extended 's|<pre data-language="([^"]+?)">|<figure><code class="\1 full">|g' \
	| sed --regexp-extended 's|<pre class="([^"]+?)" data-language="([^"]+?)">|<figure class="\1"><code class="\2 full">|g' \
	| sed --regexp-extended 's|<pre data-language="([^"]+?)" class="([^"]+?)">|<figure class="\2"><code class="\1 full">|g' \
	| sed --regexp-extended 's|</pre>|</code></figure>|g' \
	| sed --regexp-extended 's|<em class="i">([^>]+?) &lt;([^<]+?)&gt;</em>|<i><a href="\2">\1</a></i>|g' \
	| sed --regexp-extended 's|<em class="i">([^<]+?)</em>|<i>\1</i>|g' \
	| perl -0777 -pe 's|<section(.+) class="data-start-at-([0-9]+)"|<section data-start-at="\2"\1|s' \
	| cat templates/header.html - templates/footer.html \
	| perl -pe 'chomp if eof' > "${filename%.*}.html"
done
